[toolchain]
anchor_version = "1.0.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery = "7J7gXGrdLw118Ewx38fHztkhiaqKZ3aJsjm57R5epTLC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
